apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: cat-service-config
    files:
      - application.properties
      
images:
  - name: gcr.io/pgtm-jlong/cat-service # used for Kustomize matching
    newTag: b2.20211111.221325
    newName: eduk8s-labs-w02-s004-registry.mcclain-test-stg-1079dfc.tanzu-labs.esp-staging.vmware-aws.com/cat-service
  
